### ISSUE TITLE
Feature Request: Make commas between attribute optional

### ISSUE THREAD

**Issue by dippas** [dylankbuckley/html2pug#2]
Since  2013 https://github.com/pugjs/pug/issues/662 the comma is optional in pugjs, and it is been documented here: https://github.com/pugjs/pug/pull/2103.

So whenever I need to move a big chunk of html to pug,  I have to replace the comma , since is my personal choice not having the comma cluttering the code. 

Would be great if could be an option (like a checkbox) to have the comma as separator or simple the space.

Thanks!

**Comment by dippas** [comment]
@dylankbuckley can you please take a look at this :)

**Comment by dylankbuckley** [comment]
Resolved. This is also my personal preference. Perhaps in the future could add it as an option.
